apiVersion: apps/v1
kind: Deployment
metadata:
  name: notas-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notas-api
  template:
    metadata:
      labels:
        app: notas-api
    spec:
      containers:
      - name: notas-api
        image: notas_api:latest # Aquí es donde actualizas la imagen
        ports:
        - containerPort: 80
